name: TEst Project
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Add project test
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/nookyo/projects/vars.PROJECT?type=beta
          github-token: ${{ secrets.GITHUB_TOKEN }}
